### ISSUE TITLE
front50: Specified key was too long; max key length is 767 bytes Exception

### ISSUE THREAD

**Issue by mlkmhd** [songrgg/spinnaker-compose#4]
when I want to bring up the project, the `front50` service give me the following error:

```
spin-front50        | Caused by: liquibase.exception.DatabaseException: Specified key was too long; max key length is 767 bytes [Failed SQL: CREATE TABLE front50.application_permissions (id CHAR(255) NOT NULL, body LONGTEXT NOT NULL, created_at BIGINT NOT NULL, last_modified_at BIGINT NOT NULL, last_modified_by VARCHAR(255) NOT NULL, is_deleted BIT(1) DEFAULT 0 NOT NULL, CONSTRAINT PK_APPLICATION_PERMISSIONS PRIMARY KEY (id)) engine innodb DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci]
spin-front50        | 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356) ~[liquibase-core-3.6.3.jar:na]
spin-front50        | 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57) ~[liquibase-core-3.6.3.jar:na]
spin-front50        | 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125) ~[liquibase-core-3.6.3.jar:na]
spin-front50        | 	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229) ~[liquibase-core-3.6.3.jar:na]
spin-front50        | 	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211) ~[liquibase-core-3.6.3.jar:na]
spin-front50        | 	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600) ~[liquibase-core-3.6.3.jar:na]
spin-front50        | 	... 213 common frames omitted
spin-front50        | Caused by: java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
spin-front50        | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.16.jar:8.0.16]
spin-front50        | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.16.jar:8.0.16]
spin-front50        | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.16.jar:8.0.16]
spin-front50        | 	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:782) ~[mysql-connector-java-8.0.16.jar:8.0.16]
spin-front50        | 	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666) ~[mysql-connector-java-8.0.16.jar:8.0.16]
spin-front50        | 	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352) ~[liquibase-core-3.6.3.jar:na]
spin-front50        | 	... 218 common frames omitted
```

I created the mysql service exactly as the documentation described

**Comment by Tiny-wlx** [comment]
+1
